// This file is auto-generated by content-index-plugin. Do not edit manually.
import type { ContentItem } from '../../types/content';

export const contentIndex: ContentItem[] = [
  {
    "path": "life/reading-notes",
    "title": "reading-notes",
    "date": "2025-12-01",
    "summary": "读书笔记"
  },
  {
    "path": "projects/blog-project",
    "title": "blog-project",
    "date": "2025-12-01",
    "summary": "个人博客开发记录"
  },
  {
    "path": "tech/react-intro",
    "title": "react-intro",
    "date": "2025-12-01",
    "summary": "React入门指南"
  },
  {
    "path": "tech/typescript-basics",
    "title": "typescript-basics",
    "date": "2025-12-01",
    "summary": "TypeScript基础教程"
  }
]