import { Plugin } from 'vite';
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { fileURLToPath } from 'url';

// Import types for type safety in generated index.ts
import type { ContentItem } from '../types/content';

export default function contentIndexPlugin(): Plugin {
    const __dirname = path.dirname(fileURLToPath(new URL('./', import.meta.url)));

    return {
        name: 'content-index-plugin',
        buildStart: async () => {
            const contentDir = path.resolve(__dirname, '../src/content');
            const indexFilePath = path.resolve(contentDir, 'index.ts');
            const files: { path: string; title: string; date: string; summary: string }[] = [];

            const walk = (dir: string) => {
                const entries = fs.readdirSync(dir, { withFileTypes: true });
                for (const entry of entries) {
                    const fullPath = path.join(dir, entry.name);
                    if (entry.isDirectory()) {
                        walk(fullPath);
                    } else if (entry.name.endsWith('.md')) {
                        const content = fs.readFileSync(fullPath, 'utf-8');
                        const { data, content: rawContent } = matter(content);
                        const title = data.title || entry.name.replace(/\.md$/, '');
                        const date = data.date || new Date().toISOString().split('T')[0];
                        const summary = rawContent.split('\n')[0]?.replace(/^# /, '') || '';

                        // Use path.relative to safely compute relative path from contentDir
                        const relativePath = path.relative(contentDir, fullPath);
                        const cleanPath = relativePath.replace(/\.md$/, '');
                        files.push({
                            path: cleanPath,
                            title,
                            date,
                            summary,
                        });
                    }
                }
            };

            walk(contentDir);

            // Sort by date descending
            files.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

            const indexContent = `// This file is auto-generated by content-index-plugin. Do not edit manually.
import type { ContentItem } from '../../types/content';

export const contentIndex: ContentItem[] = ${JSON.stringify(files, null, 2)}`;

            fs.writeFileSync(indexFilePath, indexContent, 'utf-8');
            console.log(`✅ Generated content index: ${indexFilePath}`);
        },
    };
}